const fs = require('fs');
const path = require('path');

const apiKey = process.env.OPENAI_KEY_API;
const targetFile = path.join(__dirname, 'ayo-settings.js');

console.log('Starting Build (Direct Generation Strategy) - OPENAI MODE...');

console.log(`DEBUG: API KEY ENV VALUE: '${apiKey}'`);
console.log(`DEBUG: API KEY LENGTH: ${apiKey ? apiKey.length : 0}`);

if (!apiKey || apiKey.includes('KEY_HOLDER_XYZ')) {
    console.error('ERROR: OPENAI_KEY_API is missing or Invalid.');
    process.exit(1);
}

// Clean key
const cleanKey = apiKey.trim().replace(/^["']|["']$/g, '');

// Secure Content Generation
const content = `window.AYO_SETTINGS = {
    apiKey: "${cleanKey}"
};
// Generated by Build Script at ${new Date().toISOString()}
`;

try {
    const indexFile = path.join(__dirname, 'index.html');
    if (fs.existsSync(indexFile)) {
        let indexContent = fs.readFileSync(indexFile, 'utf8');
        const timestamp = new Date().getTime();

        // 1. INJECT API KEY INLINE (Simple String Replace)
        // We just replace the value string directly.
        if (indexContent.includes('PLACEHOLDER_INLINE')) {
            indexContent = indexContent.replace('PLACEHOLDER_INLINE', cleanKey);
            console.log('SUCCESS: Replaced PLACEHOLDER_INLINE with API Key.');
        } else {
            console.error('ERROR: PLACEHOLDER_INLINE not found in index.html!');
            // We do NOT exit here to allow debugging, but it's critical.
        }

        // 2. Cache Buster
        // Regex to match v=TIMESTAMP_NOW -OR- v=1234567890 (previous builds)
        indexContent = indexContent.replace(/v=[a-zA-Z0-9_]+/g, `v=${timestamp}`);

        fs.writeFileSync(indexFile, indexContent, 'utf8');
        console.log(`SUCCESS: Injected API Key INLINE and updated timestamp ${timestamp}`);
    } else {
        console.error("ERROR: index.html not found!");
        process.exit(1);
    }

} catch (err) {
    console.error('Error in build process:', err);
    process.exit(1);
}
