const fs = require('fs');
const path = require('path');

const apiKey = process.env.OPENAI_KEY_API;
const targetFile = path.join(__dirname, 'ayo-settings.js');

console.log('Starting Build (Direct Generation Strategy) - OPENAI MODE...');

console.log(`DEBUG: API KEY ENV VALUE: '${apiKey}'`);
console.log(`DEBUG: API KEY LENGTH: ${apiKey ? apiKey.length : 0}`);

if (!apiKey || apiKey.includes('KEY_HOLDER_XYZ')) {
    console.error('ERROR: OPENAI_KEY_API is missing or Invalid.');
    process.exit(1);
}

// Clean key
const cleanKey = apiKey.trim().replace(/^["']|["']$/g, '');

// Secure Content Generation
const content = `window.AYO_SETTINGS = {
    apiKey: "${cleanKey}"
};
// Generated by Build Script at ${new Date().toISOString()}
`;

try {
    const indexFile = path.join(__dirname, 'index.html');
    if (fs.existsSync(indexFile)) {
        let indexContent = fs.readFileSync(indexFile, 'utf8');
        const timestamp = new Date().getTime();

        // 1. INJECT API KEY INLINE (Replaces the placeholder script content)
        // We look for: window.AYO_SETTINGS = { apiKey: "PLACEHOLDER_INLINE" };
        const keyInjection = `window.AYO_SETTINGS = { apiKey: "${cleanKey}" };`;
        indexContent = indexContent.replace(/window\.AYO_SETTINGS\s*=\s*{\s*apiKey:\s*"PLACEHOLDER_INLINE"\s*};/, keyInjection);

        // 2. Cache Buster
        // Regex to match v=TIMESTAMP_NOW -OR- v=1234567890 (previous builds)
        indexContent = indexContent.replace(/v=[a-zA-Z0-9_]+/g, `v=${timestamp}`);

        fs.writeFileSync(indexFile, indexContent, 'utf8');
        console.log(`SUCCESS: Injected API Key INLINE and updated timestamp ${timestamp}`);
    } else {
        console.error("ERROR: index.html not found!");
        process.exit(1);
    }

} catch (err) {
    console.error('Error in build process:', err);
    process.exit(1);
}
