const fs = require('fs');
const path = require('path');

const apiKey = process.env.GEMINI_KEY_API;
const targetFile = path.join(__dirname, 'ayo-settings.js');

console.log('Starting Build (Direct Generation Strategy)...');

if (!apiKey || apiKey.includes('KEY_HOLDER_XYZ')) {
    console.error('ERROR: GEMINI_KEY_API is missing or Invalid.');
    process.exit(1);
}

// Clean key
const cleanKey = apiKey.trim().replace(/^["']|["']$/g, '');

// Secure Content Generation
const content = `window.AYO_SETTINGS = {
    apiKey: "${cleanKey}"
};
// Generated by Build Script at ${new Date().toISOString()}
`;

try {
    // 1. Write ayo-settings.js
    fs.writeFileSync(targetFile, content, 'utf8');
    console.log('SUCCESS: Generated ayo-settings.js from scratch.');

    // 2. Update index.html with cache-buster
    const indexFile = path.join(__dirname, 'index.html');
    if (fs.existsSync(indexFile)) {
        let indexContent = fs.readFileSync(indexFile, 'utf8');
        const timestamp = new Date().getTime();

        // Regex to match v=TIMESTAMP_NOW -OR- v=1234567890 (previous builds)
        // We use a broader regex: v=[a-zA-Z0-9_]+
        indexContent = indexContent.replace(/v=[a-zA-Z0-9_]+/g, `v=${timestamp}`);

        fs.writeFileSync(indexFile, indexContent, 'utf8');
        console.log(`SUCCESS: Updated index.html with timestamp ${timestamp}`);
    } else {
        console.error("ERROR: index.html not found!");
        process.exit(1);
    }

} catch (err) {
    console.error('Error in build process:', err);
    process.exit(1);
}
