"""Normalisation stricte des pays vers ISO 3166-1 alpha-2.

Porte d'entrée unique pour écrire `aya_registry.country_legal` depuis Python :
bot AYA (`parser.py`) et scripts d'ingestion (`aya/ingestion/`). Renvoie un code
valide, ou None si la valeur n'est pas reconnue. On ne fabrique jamais de code
(doctrine AYO : normaliser, jamais inventer).

Piège corrigé le 16 septembre 2026 : le raccourci `len(s) == 2 and s.isalpha()`
acceptait « 日本 », « 台灣 », « РФ » ou « ＪＰ » comme codes ISO, parce que ces
chaînes font deux caractères alphabétiques au sens Unicode. 265 entités du
registre portaient ces valeurs.

Codes valides : les 249 codes de la norme (paquet iso-codes, identique à tzdata
iso3166.tab) plus XK (Kosovo, code utilisateur employé par la Confédération,
l'UE et CLDR). La même liste vit dans `lib/aya/country-iso.ts` et dans le
trigger SQL `aya_normalize_country_legal` ; `test_country_iso.py` vérifie
qu'elles restent identiques.
"""
from __future__ import annotations

import re
import unicodedata
from typing import Optional

# codes:start
ISO_3166_ALPHA2 = frozenset("""
AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI
BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN
CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK
FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM
HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN
KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK
ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP
NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO RS RU RW
SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF
TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM US UY UZ VA VC VE VG VI
VN VU WF WS YE YT ZA ZM ZW
""".split())
# codes:end

VALID_COUNTRY_CODES = ISO_3166_ALPHA2 | {"XK"}

# Codes à deux lettres hors norme dont le sens est sans ambiguïté.
# (EN, JA, CS... sont des codes de langue : on ne les convertit pas.)
CODE_ALIASES = {"UK": "GB", "EL": "GR"}

ALPHA3 = {
    "AND": "AD",
    "ARE": "AE",
    "AFG": "AF",
    "ATG": "AG",
    "AIA": "AI",
    "ALB": "AL",
    "ARM": "AM",
    "AGO": "AO",
    "ATA": "AQ",
    "ARG": "AR",
    "ASM": "AS",
    "AUT": "AT",
    "AUS": "AU",
    "ABW": "AW",
    "ALA": "AX",
    "AZE": "AZ",
    "BIH": "BA",
    "BRB": "BB",
    "BGD": "BD",
    "BEL": "BE",
    "BFA": "BF",
    "BGR": "BG",
    "BHR": "BH",
    "BDI": "BI",
    "BEN": "BJ",
    "BLM": "BL",
    "BMU": "BM",
    "BRN": "BN",
    "BOL": "BO",
    "BES": "BQ",
    "BRA": "BR",
    "BHS": "BS",
    "BTN": "BT",
    "BVT": "BV",
    "BWA": "BW",
    "BLR": "BY",
    "BLZ": "BZ",
    "CAN": "CA",
    "CCK": "CC",
    "COD": "CD",
    "CAF": "CF",
    "COG": "CG",
    "CHE": "CH",
    "CIV": "CI",
    "COK": "CK",
    "CHL": "CL",
    "CMR": "CM",
    "CHN": "CN",
    "COL": "CO",
    "CRI": "CR",
    "CUB": "CU",
    "CPV": "CV",
    "CUW": "CW",
    "CXR": "CX",
    "CYP": "CY",
    "CZE": "CZ",
    "DEU": "DE",
    "DJI": "DJ",
    "DNK": "DK",
    "DMA": "DM",
    "DOM": "DO",
    "DZA": "DZ",
    "ECU": "EC",
    "EST": "EE",
    "EGY": "EG",
    "ESH": "EH",
    "ERI": "ER",
    "ESP": "ES",
    "ETH": "ET",
    "FIN": "FI",
    "FJI": "FJ",
    "FLK": "FK",
    "FSM": "FM",
    "FRO": "FO",
    "FRA": "FR",
    "GAB": "GA",
    "GBR": "GB",
    "GRD": "GD",
    "GEO": "GE",
    "GUF": "GF",
    "GGY": "GG",
    "GHA": "GH",
    "GIB": "GI",
    "GRL": "GL",
    "GMB": "GM",
    "GIN": "GN",
    "GLP": "GP",
    "GNQ": "GQ",
    "GRC": "GR",
    "SGS": "GS",
    "GTM": "GT",
    "GUM": "GU",
    "GNB": "GW",
    "GUY": "GY",
    "HKG": "HK",
    "HMD": "HM",
    "HND": "HN",
    "HRV": "HR",
    "HTI": "HT",
    "HUN": "HU",
    "IDN": "ID",
    "IRL": "IE",
    "ISR": "IL",
    "IMN": "IM",
    "IND": "IN",
    "IOT": "IO",
    "IRQ": "IQ",
    "IRN": "IR",
    "ISL": "IS",
    "ITA": "IT",
    "JEY": "JE",
    "JAM": "JM",
    "JOR": "JO",
    "JPN": "JP",
    "KEN": "KE",
    "KGZ": "KG",
    "KHM": "KH",
    "KIR": "KI",
    "COM": "KM",
    "KNA": "KN",
    "PRK": "KP",
    "KOR": "KR",
    "KWT": "KW",
    "CYM": "KY",
    "KAZ": "KZ",
    "LAO": "LA",
    "LBN": "LB",
    "LCA": "LC",
    "LIE": "LI",
    "LKA": "LK",
    "LBR": "LR",
    "LSO": "LS",
    "LTU": "LT",
    "LUX": "LU",
    "LVA": "LV",
    "LBY": "LY",
    "MAR": "MA",
    "MCO": "MC",
    "MDA": "MD",
    "MNE": "ME",
    "MAF": "MF",
    "MDG": "MG",
    "MHL": "MH",
    "MKD": "MK",
    "MLI": "ML",
    "MMR": "MM",
    "MNG": "MN",
    "MAC": "MO",
    "MNP": "MP",
    "MTQ": "MQ",
    "MRT": "MR",
    "MSR": "MS",
    "MLT": "MT",
    "MUS": "MU",
    "MDV": "MV",
    "MWI": "MW",
    "MEX": "MX",
    "MYS": "MY",
    "MOZ": "MZ",
    "NAM": "NA",
    "NCL": "NC",
    "NER": "NE",
    "NFK": "NF",
    "NGA": "NG",
    "NIC": "NI",
    "NLD": "NL",
    "NOR": "NO",
    "NPL": "NP",
    "NRU": "NR",
    "NIU": "NU",
    "NZL": "NZ",
    "OMN": "OM",
    "PAN": "PA",
    "PER": "PE",
    "PYF": "PF",
    "PNG": "PG",
    "PHL": "PH",
    "PAK": "PK",
    "POL": "PL",
    "SPM": "PM",
    "PCN": "PN",
    "PRI": "PR",
    "PSE": "PS",
    "PRT": "PT",
    "PLW": "PW",
    "PRY": "PY",
    "QAT": "QA",
    "REU": "RE",
    "ROU": "RO",
    "SRB": "RS",
    "RUS": "RU",
    "RWA": "RW",
    "SAU": "SA",
    "SLB": "SB",
    "SYC": "SC",
    "SDN": "SD",
    "SWE": "SE",
    "SGP": "SG",
    "SHN": "SH",
    "SVN": "SI",
    "SJM": "SJ",
    "SVK": "SK",
    "SLE": "SL",
    "SMR": "SM",
    "SEN": "SN",
    "SOM": "SO",
    "SUR": "SR",
    "SSD": "SS",
    "STP": "ST",
    "SLV": "SV",
    "SXM": "SX",
    "SYR": "SY",
    "SWZ": "SZ",
    "TCA": "TC",
    "TCD": "TD",
    "ATF": "TF",
    "TGO": "TG",
    "THA": "TH",
    "TJK": "TJ",
    "TKL": "TK",
    "TLS": "TL",
    "TKM": "TM",
    "TUN": "TN",
    "TON": "TO",
    "TUR": "TR",
    "TTO": "TT",
    "TUV": "TV",
    "TWN": "TW",
    "TZA": "TZ",
    "UKR": "UA",
    "UGA": "UG",
    "UMI": "UM",
    "USA": "US",
    "URY": "UY",
    "UZB": "UZ",
    "VAT": "VA",
    "VCT": "VC",
    "VEN": "VE",
    "VGB": "VG",
    "VIR": "VI",
    "VNM": "VN",
    "VUT": "VU",
    "WLF": "WF",
    "WSM": "WS",
    "YEM": "YE",
    "MYT": "YT",
    "ZAF": "ZA",
    "ZMB": "ZM",
    "ZWE": "ZW",
}

# Noms anglais de la norme (paquet iso-codes).
_ISO_NAMES = {
    "Andorra": "AD",
    "United Arab Emirates": "AE",
    "Afghanistan": "AF",
    "Antigua and Barbuda": "AG",
    "Anguilla": "AI",
    "Albania": "AL",
    "Armenia": "AM",
    "Angola": "AO",
    "Antarctica": "AQ",
    "Argentina": "AR",
    "American Samoa": "AS",
    "Austria": "AT",
    "Australia": "AU",
    "Aruba": "AW",
    "Åland Islands": "AX",
    "Azerbaijan": "AZ",
    "Bosnia and Herzegovina": "BA",
    "Barbados": "BB",
    "Bangladesh": "BD",
    "Belgium": "BE",
    "Burkina Faso": "BF",
    "Bulgaria": "BG",
    "Bahrain": "BH",
    "Burundi": "BI",
    "Benin": "BJ",
    "Saint Barthélemy": "BL",
    "Bermuda": "BM",
    "Brunei Darussalam": "BN",
    "Bolivia, Plurinational State of": "BO",
    "Bolivia": "BO",
    "Bonaire, Sint Eustatius and Saba": "BQ",
    "Brazil": "BR",
    "Bahamas": "BS",
    "Bhutan": "BT",
    "Bouvet Island": "BV",
    "Botswana": "BW",
    "Belarus": "BY",
    "Belize": "BZ",
    "Canada": "CA",
    "Cocos (Keeling) Islands": "CC",
    "Congo, The Democratic Republic of the": "CD",
    "Central African Republic": "CF",
    "Congo": "CG",
    "Switzerland": "CH",
    "Côte d'Ivoire": "CI",
    "Cook Islands": "CK",
    "Chile": "CL",
    "Cameroon": "CM",
    "China": "CN",
    "Colombia": "CO",
    "Costa Rica": "CR",
    "Cuba": "CU",
    "Cabo Verde": "CV",
    "Curaçao": "CW",
    "Christmas Island": "CX",
    "Cyprus": "CY",
    "Czechia": "CZ",
    "Germany": "DE",
    "Djibouti": "DJ",
    "Denmark": "DK",
    "Dominica": "DM",
    "Dominican Republic": "DO",
    "Algeria": "DZ",
    "Ecuador": "EC",
    "Estonia": "EE",
    "Egypt": "EG",
    "Western Sahara": "EH",
    "Eritrea": "ER",
    "Spain": "ES",
    "Ethiopia": "ET",
    "Finland": "FI",
    "Fiji": "FJ",
    "Falkland Islands (Malvinas)": "FK",
    "Micronesia, Federated States of": "FM",
    "Faroe Islands": "FO",
    "France": "FR",
    "Gabon": "GA",
    "United Kingdom": "GB",
    "Grenada": "GD",
    "Georgia": "GE",
    "French Guiana": "GF",
    "Guernsey": "GG",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Greenland": "GL",
    "Gambia": "GM",
    "Guinea": "GN",
    "Guadeloupe": "GP",
    "Equatorial Guinea": "GQ",
    "Greece": "GR",
    "South Georgia and the South Sandwich Islands": "GS",
    "Guatemala": "GT",
    "Guam": "GU",
    "Guinea-Bissau": "GW",
    "Guyana": "GY",
    "Hong Kong": "HK",
    "Heard Island and McDonald Islands": "HM",
    "Honduras": "HN",
    "Croatia": "HR",
    "Haiti": "HT",
    "Hungary": "HU",
    "Indonesia": "ID",
    "Ireland": "IE",
    "Israel": "IL",
    "Isle of Man": "IM",
    "India": "IN",
    "British Indian Ocean Territory": "IO",
    "Iraq": "IQ",
    "Iran, Islamic Republic of": "IR",
    "Iran": "IR",
    "Iceland": "IS",
    "Italy": "IT",
    "Jersey": "JE",
    "Jamaica": "JM",
    "Jordan": "JO",
    "Japan": "JP",
    "Kenya": "KE",
    "Kyrgyzstan": "KG",
    "Cambodia": "KH",
    "Kiribati": "KI",
    "Comoros": "KM",
    "Saint Kitts and Nevis": "KN",
    "Korea, Democratic People's Republic of": "KP",
    "North Korea": "KP",
    "Korea, Republic of": "KR",
    "South Korea": "KR",
    "Kuwait": "KW",
    "Cayman Islands": "KY",
    "Kazakhstan": "KZ",
    "Lao People's Democratic Republic": "LA",
    "Laos": "LA",
    "Lebanon": "LB",
    "Saint Lucia": "LC",
    "Liechtenstein": "LI",
    "Sri Lanka": "LK",
    "Liberia": "LR",
    "Lesotho": "LS",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Latvia": "LV",
    "Libya": "LY",
    "Morocco": "MA",
    "Monaco": "MC",
    "Moldova, Republic of": "MD",
    "Moldova": "MD",
    "Montenegro": "ME",
    "Saint Martin (French part)": "MF",
    "Madagascar": "MG",
    "Marshall Islands": "MH",
    "North Macedonia": "MK",
    "Mali": "ML",
    "Myanmar": "MM",
    "Mongolia": "MN",
    "Macao": "MO",
    "Northern Mariana Islands": "MP",
    "Martinique": "MQ",
    "Mauritania": "MR",
    "Montserrat": "MS",
    "Malta": "MT",
    "Mauritius": "MU",
    "Maldives": "MV",
    "Malawi": "MW",
    "Mexico": "MX",
    "Malaysia": "MY",
    "Mozambique": "MZ",
    "Namibia": "NA",
    "New Caledonia": "NC",
    "Niger": "NE",
    "Norfolk Island": "NF",
    "Nigeria": "NG",
    "Nicaragua": "NI",
    "Netherlands": "NL",
    "Norway": "NO",
    "Nepal": "NP",
    "Nauru": "NR",
    "Niue": "NU",
    "New Zealand": "NZ",
    "Oman": "OM",
    "Panama": "PA",
    "Peru": "PE",
    "French Polynesia": "PF",
    "Papua New Guinea": "PG",
    "Philippines": "PH",
    "Pakistan": "PK",
    "Poland": "PL",
    "Saint Pierre and Miquelon": "PM",
    "Pitcairn": "PN",
    "Puerto Rico": "PR",
    "Palestine, State of": "PS",
    "Portugal": "PT",
    "Palau": "PW",
    "Paraguay": "PY",
    "Qatar": "QA",
    "Réunion": "RE",
    "Romania": "RO",
    "Serbia": "RS",
    "Russian Federation": "RU",
    "Rwanda": "RW",
    "Saudi Arabia": "SA",
    "Solomon Islands": "SB",
    "Seychelles": "SC",
    "Sudan": "SD",
    "Sweden": "SE",
    "Singapore": "SG",
    "Saint Helena, Ascension and Tristan da Cunha": "SH",
    "Slovenia": "SI",
    "Svalbard and Jan Mayen": "SJ",
    "Slovakia": "SK",
    "Sierra Leone": "SL",
    "San Marino": "SM",
    "Senegal": "SN",
    "Somalia": "SO",
    "Suriname": "SR",
    "South Sudan": "SS",
    "Sao Tome and Principe": "ST",
    "El Salvador": "SV",
    "Sint Maarten (Dutch part)": "SX",
    "Syrian Arab Republic": "SY",
    "Syria": "SY",
    "Eswatini": "SZ",
    "Turks and Caicos Islands": "TC",
    "Chad": "TD",
    "French Southern Territories": "TF",
    "Togo": "TG",
    "Thailand": "TH",
    "Tajikistan": "TJ",
    "Tokelau": "TK",
    "Timor-Leste": "TL",
    "Turkmenistan": "TM",
    "Tunisia": "TN",
    "Tonga": "TO",
    "Türkiye": "TR",
    "Trinidad and Tobago": "TT",
    "Tuvalu": "TV",
    "Taiwan, Province of China": "TW",
    "Taiwan": "TW",
    "Tanzania, United Republic of": "TZ",
    "Tanzania": "TZ",
    "Ukraine": "UA",
    "Uganda": "UG",
    "United States Minor Outlying Islands": "UM",
    "United States": "US",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Holy See (Vatican City State)": "VA",
    "Saint Vincent and the Grenadines": "VC",
    "Venezuela, Bolivarian Republic of": "VE",
    "Venezuela": "VE",
    "Virgin Islands, British": "VG",
    "Virgin Islands, U.S.": "VI",
    "Viet Nam": "VN",
    "Vietnam": "VN",
    "Vanuatu": "VU",
    "Wallis and Futuna": "WF",
    "Samoa": "WS",
    "Yemen": "YE",
    "Mayotte": "YT",
    "South Africa": "ZA",
    "Zambia": "ZM",
    "Zimbabwe": "ZW",
}

# Noms usuels et noms locaux rencontrés dans les sources. Les abréviations
# ambiguës (РБ, КГ, КЗ) et les villes (大阪) n'y figurent pas : une entité
# « КГ » du registre était à Saint-Pétersbourg, pas au Kirghizistan.
_ALIASES = {
    # Anglais et variantes
    "USA": "US", "U.S.A": "US", "U.S": "US", "America": "US", "United States of America": "US",
    "UK": "GB", "Great Britain": "GB", "Britain": "GB", "England": "GB", "Scotland": "GB",
    "Wales": "GB", "Northern Ireland": "GB", "Holland": "NL", "The Netherlands": "NL",
    "UAE": "AE", "Korea": "KR", "Russia": "RU", "Czech Republic": "CZ", "Turkey": "TR",
    "Macau": "MO", "Vatican": "VA", "Ivory Coast": "CI", "Cape Verde": "CV", "Swaziland": "SZ",
    "Burma": "MM", "East Timor": "TL", "Kosovo": "XK",
    # Europe, langues locales
    "Suisse": "CH", "Schweiz": "CH", "Svizzera": "CH", "Svizra": "CH",
    "Deutschland": "DE", "Allemagne": "DE", "Österreich": "AT", "Autriche": "AT",
    "España": "ES", "Espagne": "ES", "Italia": "IT", "Italie": "IT", "Nederland": "NL",
    "Pays-Bas": "NL", "Belgique": "BE", "België": "BE", "Belgien": "BE", "Royaume-Uni": "GB",
    "États-Unis": "US", "Polska": "PL", "Sverige": "SE", "Norge": "NO", "Danmark": "DK",
    "Suomi": "FI", "Éire": "IE", "Česká republika": "CZ", "Česko": "CZ", "Slovensko": "SK",
    "Magyarország": "HU", "România": "RO", "Hrvatska": "HR", "Slovenija": "SI",
    "Ελλάδα": "GR", "Türkiye": "TR", "Україна": "UA", "Украина": "UA",
    # Amériques
    "Brasil": "BR", "México": "MX", "Perú": "PE", "República Dominicana": "DO",
    # Russie, Europe de l'Est, Asie centrale
    "РФ": "RU", "Россия": "RU", "Российская Федерация": "RU", "Беларусь": "BY",
    "Республика Беларусь": "BY", "Белоруссия": "BY", "Казахстан": "KZ", "Қазақстан": "KZ",
    "Кыргызстан": "KG", "Киргизия": "KG", "Узбекистан": "UZ",
    # Chinois, japonais, coréen
    "日本": "JP", "日本国": "JP", "일본": "JP", "中国": "CN", "中國": "CN",
    "中华人民共和国": "CN", "中華人民共和國": "CN", "중국": "CN", "台灣": "TW", "台湾": "TW",
    "臺灣": "TW", "대만": "TW", "香港": "HK", "홍콩": "HK", "澳門": "MO", "澳门": "MO",
    "한국": "KR", "대한민국": "KR", "韓國": "KR", "韩国": "KR", "美国": "US", "美國": "US",
    "米国": "US", "アメリカ": "US", "미국": "US", "英国": "GB", "英國": "GB", "イギリス": "GB",
    "영국": "GB", "法国": "FR", "法國": "FR", "フランス": "FR", "프랑스": "FR", "德国": "DE",
    "德國": "DE", "ドイツ": "DE", "독일": "DE", "澳大利亚": "AU", "澳大利亞": "AU", "澳洲": "AU",
    "オーストラリア": "AU", "호주": "AU", "오스트레일리아": "AU", "加拿大": "CA", "カナダ": "CA",
    "캐나다": "CA", "新加坡": "SG", "シンガポール": "SG", "싱가포르": "SG", "瑞士": "CH",
    "スイス": "CH", "스위스": "CH",
}

_ASCII2 = re.compile(r"[A-Za-z]{2}")
_ASCII3 = re.compile(r"[A-Za-z]{3}")


def _clean(value) -> str:
    text = unicodedata.normalize("NFKC", str(value)).replace("\u2019", "'")
    return " ".join(text.split()).strip(" .")


def _strip_accents(text: str) -> str:
    return "".join(c for c in unicodedata.normalize("NFKD", text) if not unicodedata.combining(c))


def _build_name_index() -> dict:
    index = {}
    for source in (_ISO_NAMES, _ALIASES):
        for name, code in source.items():
            if code not in VALID_COUNTRY_CODES:
                raise ValueError(f"alias {name!r} -> {code!r} hors liste ISO")
            key = _clean(name).casefold()
            index[key] = code
            index.setdefault(_strip_accents(key), code)
    return index


_NAME_INDEX = _build_name_index()


def to_iso_country(value) -> Optional[str]:
    """Code ISO 3166-1 alpha-2 (ou XK) correspondant à `value`, sinon None."""
    if value is None:
        return None
    text = _clean(value)
    if not text:
        return None
    if _ASCII2.fullmatch(text):
        code = CODE_ALIASES.get(text.upper(), text.upper())
        return code if code in VALID_COUNTRY_CODES else None
    key = text.casefold()
    if _ASCII3.fullmatch(text) and text.upper() in ALPHA3:
        return ALPHA3[text.upper()]
    return _NAME_INDEX.get(key) or _NAME_INDEX.get(_strip_accents(key))


def is_iso_country(code) -> bool:
    """Vrai si `code` est déjà un code pays valide (ISO 3166-1 alpha-2 ou XK)."""
    return isinstance(code, str) and code in VALID_COUNTRY_CODES
